// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxqoscilojosafuiwpxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4cW9zY2lsb2pvc2FmdWl3cHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTgwNDksImV4cCI6MjA2NDg5NDA0OX0.eIhZb8HBIFdRpgRCodb1lGjBJPKXSWkqCKvPXMrdN1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
    },});